In [2]:
#Importing required packages.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
%matplotlib inline
import random

In [3]:
#load the data in text form separated by commas
brainT = np.loadtxt('Braintumor.csv', delimiter = ',', skiprows = 1)

In [5]:
#check the shape
print(brainT.shape)

(3762, 14)


In [6]:
#change the format so calculations and reading are easier
np.set_printoptions(formatter = {'float': '{: 0.1f}'.format})

In [8]:
#Get the predictors
X = brainT[:, 1:]
print(X)

[[ 6.5  619.6  24.9 ...  4.5  1.0  0.0]
 [ 8.7  806.0  28.4 ...  3.2  1.0  0.0]
 [ 7.3  1143.8  33.8 ...  6.0  1.0  0.0]
 ...
 [ 18.0  1151.6  33.9 ...  5.1  1.0  0.0]
 [ 13.3  945.7  30.8 ...  6.4  0.9  0.0]
 [ 6.1  480.9  21.9 ...  6.8  0.9  0.0]]


In [9]:
#Get the target variable
Y = brainT[:, :1]
print(Y)

[[ 0.0]
 [ 0.0]
 [ 1.0]
 ...
 [ 0.0]
 [ 0.0]
 [ 0.0]]


In [12]:
#import tensorflow for neuron netowrk
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
#build model
model = Sequential()
model.add(Dense(8, input_dim = len(X[0, :]), activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [14]:
#compile and fit the model with 500 epochs
model.compile(loss = 'binary_crossentropy', optimizer = 'rmsprop', metrics = ['accuracy'])
model.fit(x = X, y = Y, epochs = 500, verbose = 1)

Epoch 1/500
118/118 [==============================] - 2s 4ms/step - loss: 13.0658 - accuracy: 0.3647
Epoch 2/500
118/118 [==============================] - 0s 4ms/step - loss: 3.7553 - accuracy: 0.3392
Epoch 3/500
118/118 [==============================] - 0s 3ms/step - loss: 1.5574 - accuracy: 0.4301
Epoch 4/500
118/118 [==============================] - 0s 4ms/step - loss: 0.9042 - accuracy: 0.6010
Epoch 5/500
118/118 [==============================] - 0s 4ms/step - loss: 0.6370 - accuracy: 0.7196
Epoch 6/500
118/118 [==============================] - 0s 4ms/step - loss: 0.4909 - accuracy: 0.7993
Epoch 7/500
118/118 [==============================] - 0s 4ms/step - loss: 0.4315 - accuracy: 0.8424
Epoch 8/500
118/118 [==============================] - 0s 3ms/step - loss: 0.3956 - accuracy: 0.8535
Epoch 9/500
118/118 [==============================] - 0s 3ms/step - loss: 0.3703 - accuracy: 0.8652
Epoch 10/500
118/118 [==============================] - 0s 4ms/step - loss: 0.3597 - accur

118/118 [==============================] - 0s 3ms/step - loss: 0.1270 - accuracy: 0.9492
Epoch 82/500
118/118 [==============================] - 0s 3ms/step - loss: 0.1318 - accuracy: 0.9484
Epoch 83/500
118/118 [==============================] - 0s 3ms/step - loss: 0.1310 - accuracy: 0.9498
Epoch 84/500
118/118 [==============================] - 0s 3ms/step - loss: 0.1307 - accuracy: 0.9551
Epoch 85/500
118/118 [==============================] - 0s 3ms/step - loss: 0.1266 - accuracy: 0.9524
Epoch 86/500
118/118 [==============================] - 0s 3ms/step - loss: 0.1314 - accuracy: 0.9474
Epoch 87/500
118/118 [==============================] - 0s 3ms/step - loss: 0.1279 - accuracy: 0.9519
Epoch 88/500
118/118 [==============================] - 0s 3ms/step - loss: 0.1310 - accuracy: 0.9503
Epoch 89/500
118/118 [==============================] - 0s 3ms/step - loss: 0.1264 - accuracy: 0.9543
Epoch 90/500
118/118 [==============================] - 0s 3ms/step - loss: 0.1241 - accuracy: 

118/118 [==============================] - 0s 3ms/step - loss: 0.0940 - accuracy: 0.9633
Epoch 161/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0947 - accuracy: 0.9654
Epoch 162/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0974 - accuracy: 0.9654
Epoch 163/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0965 - accuracy: 0.9657
Epoch 164/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0947 - accuracy: 0.9646
Epoch 165/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0954 - accuracy: 0.9657
Epoch 166/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0914 - accuracy: 0.9646
Epoch 167/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0928 - accuracy: 0.9660
Epoch 168/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0976 - accuracy: 0.9638
Epoch 169/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0941 - a

118/118 [==============================] - 0s 4ms/step - loss: 0.0812 - accuracy: 0.9734
Epoch 240/500
118/118 [==============================] - 0s 4ms/step - loss: 0.0792 - accuracy: 0.9710
Epoch 241/500
118/118 [==============================] - 0s 4ms/step - loss: 0.0718 - accuracy: 0.9750
Epoch 242/500
118/118 [==============================] - 0s 4ms/step - loss: 0.0783 - accuracy: 0.9702
Epoch 243/500
118/118 [==============================] - 0s 4ms/step - loss: 0.0789 - accuracy: 0.9708
Epoch 244/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0854 - accuracy: 0.9681
Epoch 245/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0826 - accuracy: 0.9729
Epoch 246/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0870 - accuracy: 0.9673
Epoch 247/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0817 - accuracy: 0.9708
Epoch 248/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0802 - a

118/118 [==============================] - 0s 3ms/step - loss: 0.0694 - accuracy: 0.9740
Epoch 319/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0716 - accuracy: 0.9761
Epoch 320/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0740 - accuracy: 0.9745
Epoch 321/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0729 - accuracy: 0.9737
Epoch 322/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0750 - accuracy: 0.9718
Epoch 323/500
118/118 [==============================] - 0s 4ms/step - loss: 0.0781 - accuracy: 0.9734
Epoch 324/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0733 - accuracy: 0.9718
Epoch 325/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0722 - accuracy: 0.9763
Epoch 326/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0696 - accuracy: 0.9758
Epoch 327/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0711 - a

118/118 [==============================] - 0s 3ms/step - loss: 0.0613 - accuracy: 0.9779
Epoch 398/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0738 - accuracy: 0.9755
Epoch 399/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0699 - accuracy: 0.9769
Epoch 400/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0662 - accuracy: 0.9766
Epoch 401/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0659 - accuracy: 0.9763
Epoch 402/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0639 - accuracy: 0.9798
Epoch 403/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0627 - accuracy: 0.9790
Epoch 404/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0640 - accuracy: 0.9785
Epoch 405/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0667 - accuracy: 0.9779
Epoch 406/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0732 - a

118/118 [==============================] - 0s 3ms/step - loss: 0.0589 - accuracy: 0.9782
Epoch 477/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0622 - accuracy: 0.9801
Epoch 478/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0659 - accuracy: 0.9782
Epoch 479/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0663 - accuracy: 0.9763
Epoch 480/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0692 - accuracy: 0.9761
Epoch 481/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0721 - accuracy: 0.9758
Epoch 482/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0676 - accuracy: 0.9769
Epoch 483/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0688 - accuracy: 0.9777
Epoch 484/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0693 - accuracy: 0.9777
Epoch 485/500
118/118 [==============================] - 0s 3ms/step - loss: 0.0643 - a

In [15]:
accuracy = model.evaluate(X, Y)

118/118 [==============================] - 1s 3ms/step - loss: 0.0770 - accuracy: 0.9702
